### ISSUE TITLE
Non-string variables

### ISSUE THREAD

**Issue by ryanewk** [hashicorp/terraform-k8s#11]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Most (all?) of our modules have some variables that have a data type other than string (maps, lists, etc.). Right now, it appears the Terraform Operator only supports string type variables. It would be great if the operator had support for the different Terraform [variable data types](https://www.terraform.io/docs/configuration/variables.html#type-constraints).

### Potential Terraform Configuration

```yaml
variables:
- key: tags
  value: <need to somehow supply a map here or via a configMapKeyRef>
  sensitive: false
  environmentVariable: false
```
