### ISSUE TITLE
CRD validation incomplete

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-k8s#126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files
```yaml
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: workspace-sample
spec:
  # Add fields here
  organization: k8s-provider
  secretsMountPath: /tmp
```

### Debug Output
```log
2022-02-18T16:26:38.738+0100	ERROR	controller.workspace-controller	Reconciler error	{"name": "workspace-sample", "namespace": "default", "error": "template: main.tf:21:19: executing \"main.tf\" at <.Spec.Module.Source>: nil pointer evaluating *v1alpha1.Module.Source"}
```

### References

* #0000
