### ISSUE TITLE
Run dependencies between workspaces

### ISSUE THREAD

**Issue by OlegGorj** [hashicorp/terraform-k8s#128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Implement run dependencies between workspaces, as in one workspace won't trigger the run until specified pre-requisite workspace finish its run(s). This can be used to create tree-like running hierarchies for the workspaces, and achieve fairly complex orchestration of multiple runs.

Suggest using Run Trigger AP https://www.terraform.io/cloud-docs/api-docs/run-triggers

### Potential Terraform Configuration

Workspace configuration may look like this:
```
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
 name: demo
spec:

 # The workspace name that needs to finish the run before
 #  this workspace can be triggered
 workspaceTrigger: <Name-of-pre-requisite-workspace>

 organization: demo
 secretsMountPath: "/tmp/secrets"
 module:
   source: "github.com/koikonom/terraform-nullresource-example"
 variables:
   - key: CONFIRM_DESTROY
     value: "1"
     sensitive: false
     environmentVariable: true
 outputs:
   - key: pet
     moduleOutputName: rofl
```

### References

Run Trigger AP https://www.terraform.io/cloud-docs/api-docs/run-triggers
