### ISSUE TITLE
Optional module directory for git modules

### ISSUE THREAD

**Issue by eakman-nomad** [hashicorp/terraform-k8s#138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using a git repository as a `source` for a `Workspace`, I would like to be able to point to a subdirectory where the module lives. e.g.:
```
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: pubsub
spec:
  sshKeyID: sshkey-frVpWGjJBNof8Kth
  organization: MyOrg
  secretsMountPath: "/tmp/secrets"
  module:
    source: "git@github.com:MyOrg/my-repo.git"
    sourceDir: "pubsub/" # <-- THIS
```

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
