### ISSUE TITLE
Support for secrets from Azure KeyVault (and potentially other secret management backends)

### ISSUE THREAD

**Issue by OlegGorj** [hashicorp/terraform-k8s#140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At this time, the only possibility to manage secrets as via K8s secrets and referenced in CRD.
We're looking to expand the secrets management capabilities to include reading secrets from Azure KeyVaults. 

### Potential Terraform Configuration

The proposed change could take a form as part of CRD manifest as the following:

```yaml
---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: salutations
  azurekeyvault: my-key-vault.vault.azure.net   <--- here, specify the name of KV
spec:
  organization: hashicorp-team-demo
  module:
    source: "git::https://github.com/mygit/queues.git"
  variables:
    - key: application
      value: azurekeyvault@my-secret    <-- here, reference KV and secret name
      sensitive: true
      environmentVariable: false
```

Variable behaviour goes as:
1)  if `value` not specified as part of the block - usual route: read secret's value from k8s secret
2) if  `value` specified as part of the block (i.e. `value: azurekeyvault@my-secret` ) parse it and pull the secret from secret backed specified, in this case `azurekeyvault`. 
This could be expanded further to support multiple back-ends such as AWS KMS, HC Vault, etc.

### References

n/a
