### ISSUE TITLE
Panic in outputs from state

### ISSUE THREAD

**Issue by goller** [hashicorp/terraform-k8s#18]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### terraform-k8s & Kubernetes Version

hashicorp/terraform-k8s:0.1.1-alpha

### Terraform Configuration Files

```hcl
terraform {
           backend "remote" {
             organization = "****"

             workspaces {
               name = "clusters-potassium"
             }
           }
         }
         variable "region" {}
         output "cluster_endpoint" {
           value = module.operator.cluster_endpoint
         }
         output "security_group_id" {
           value = module.operator.cluster_security_group_id
         }
         output "endpoint" {
           value = module.operator.cluster_endpoint
         }
         output "config_map_aws_auth" {
           value = module.operator.config_map_aws_auth
         }
         output "kubectl_config" {
           value = module.operator.kubectl_config
         }
         output "region" {
           value = module.operator.region
         }
         module "operator" {
           source = "terraform-aws-modules/eks/aws//examples/launch_templates"
           version = "11.0.0"
           region = var.region
         }

```

### Debug Output
Logs: https://gist.github.com/goller/0e80675fd1f5b57d3e53c1fa49ce38e0

With this (edited) output state:

```json
        "config_map_aws_auth": {
            "value": [
                {
                    "binary_data": null,
                    "data": {
                        "mapAccounts": "[]\n",
                        "mapRoles": "- \"groups\":\n  - \"system:bootstrappers\"\n  - \"system:nodes\"\n  \"rolearn\": \"arn:aws:iam::****:role/****\"\n  \"username\": \"system:node:{{EC2PrivateDNSName}}\"\n",
                        "mapUsers": "[]\n"
                    },
```

I get a panic here:

https://github.com/hashicorp/terraform-k8s/blob/0424fad2f0f4d750bf000c2fee3130e4370870f4/operator/pkg/controller/workspace/tfc_output.go#L75

```
panic(0x19030e0, 0x1f84160)
	/opt/hostedtoolcache/go/1.13.8/x64/src/runtime/panic.go:679 +0x1b2
github.com/zclconf/go-cty/cty.Value.ElementIterator(0x1ff4d80, 0xc00083ca20, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.3.1/cty/value_ops.go:1038 +0x101
github.com/hashicorp/terraform-k8s/operator/pkg/controller/workspace.convertValueToString(0x1ff4d80, 0xc00083ca20, 0x0, 0x0, 0xc0007ac953, 0xb)
	/home/runner/work/terraform-k8s/terraform-k8s/operator/pkg/controller/workspace/tfc_output.go:75 +0x8d8

```

I added this

```diff
diff --git a/operator/pkg/controller/workspace/tfc_output.go b/operator/pkg/controller/workspace/tfc_output.go
index 28da8ca..4eb33cc 100644
--- a/operator/pkg/controller/workspace/tfc_output.go
+++ b/operator/pkg/controller/workspace/tfc_output.go
@@ -23,6 +23,9 @@ func (t *TerraformCloudClient) GetStateVersionDownloadURL(workspaceID string) (s
 }

 func convertValueToString(val cty.Value) string {
+       if val.IsNull() {
+               return ""
+       }
        ty := val.Type()
        switch {
        case ty.IsPrimitiveType():

```

However, another panic will follow here:
https://github.com/hashicorp/terraform-k8s/blob/0424fad2f0f4d750bf000c2fee3130e4370870f4/operator/pkg/controller/workspace/tfc_output.go#L40

as a result of ```"mapAccounts": "[]\n",``` not being a string.

I tried this diff

```diff
diff --git a/operator/pkg/controller/workspace/tfc_output.go b/operator/pkg/controller/workspace/tfc_output.go
index 28da8ca..4eb33cc 100644
--- a/operator/pkg/controller/workspace/tfc_output.go
+++ b/operator/pkg/controller/workspace/tfc_output.go
@@ -36,9 +39,10 @@ func convertValueToString(val cty.Value) string {
                                // and just allow it to be printed out directly
                                if err == nil && !ty.IsPrimitiveType() && strings.TrimSpace(val.AsString()) != "null" {
                                        jv, err := ctyjson.Unmarshal(src, ty)
-                                       if err == nil {
-                                               return jv.AsString()
+                                       if err != nil {
+                                               return ""
                                        }
+                                       return convertValueToString(jv)
                                }
                        }
                        return `"` + val.AsString() + `"`
```

This solution is likely not correct, but, it stops the panic.

### Expected Behavior

Needs to handle string empty JSON arrays.

I'm honestly not sure how the operator should represent the output of these embedded strings.

### Actual Behavior

Panic and unable to use operator

### Steps to Reproduce

`kubectl apply` this:

```yaml
---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: myname
spec:
  organization: ****
  secretsMountPath: "/tmp/secrets"
  module:
    source: "terraform-aws-modules/eks/aws//examples/launch_templates"
    version: "11.0.0"
  outputs:
    - key: cluster_endpoint
      moduleOutputName: cluster_endpoint
    - key: security_group_id
      moduleOutputName: cluster_security_group_id
    - key: endpoint
      moduleOutputName: cluster_endpoint
    - key: config_map_aws_auth
      moduleOutputName: config_map_aws_auth
    - key: kubectl_config
      moduleOutputName: kubectl_config
    - key: region
      moduleOutputName: region
  variables:
    - key: region
      value: us-east-1
      sensitive: false
      environmentVariable: false
    - key: AWS_DEFAULT_REGION
      valueFrom:
        configMapKeyRef:
          name: aws-configuration
          key: region
      sensitive: false
      environmentVariable: true
    - key: AWS_ACCESS_KEY_ID
      sensitive: true
      environmentVariable: true
    - key: AWS_SECRET_ACCESS_KEY
      sensitive: true
      environmentVariable: true
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true
```

### References

Similar problems for other users of cty:

https://github.com/hashicorp/terraform/pull/23492
https://github.com/hashicorp/terraform-k8s/issues/11
https://github.com/hashicorp/terraform-k8s/issues/12

* #0000
