### ISSUE TITLE
Use ConfigMap for Workspace Variables

### ISSUE THREAD

**Issue by joatmon08** [hashicorp/terraform-k8s#2]
Besides directly hard-coding the value, support usage of ConfigMap `valueFrom` directive to reference the workspace variable value from ConfigMap.

```yaml
  variables:
    - key: hello
       valueFrom:
         configMapKeyRef:
           name: workspace
           key: hello
      sensitive: false
      environmentVariable: false
```
