### ISSUE TITLE
Support SSH Key assignment in created workspace

### ISSUE THREAD

**Issue by rojopolis** [hashicorp/terraform-k8s#25]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform Cloud will accept a reference to an SSH key for access to private module repos however, the operator doesn't currently expose this as a configuration option.

### Potential Terraform Configuration
``` yaml
---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: bucket
spec:
  sshKeyId: "abc-123"
  organization: parkside_securities
  secretsMountPath: "/tmp/secrets"
  module:
    source: "github.com/rojopolis/terraform-aws-s3-bucket.git"
  outputs:
    - key: bucket
      moduleOutputName: bucket
  variables:
    - key: bucket
      value: entertainment-720-3399
      sensitive: false
      environmentVariable: false
```

### References
https://github.com/hashicorp/go-tfe/blob/7a20a8c2dbd17a5731c35b452b1ac756ad124157/workspace.go#L589
