### ISSUE TITLE
Video demo Status Outputs Attribute and Key fields are incorrect

### ISSUE THREAD

**Issue by jbayer** [hashicorp/terraform-k8s#3]
The output from the video demo shows

```
Outputs:
  Attribute: pet
  Key: my_pet
  Value: 
```
I believe the Attribute and Key fields are not correct as they are currently output as:

```
Outputs:
  Attribute: my_pet
  Key: 
  Value: adjusted-platypus
```

I suspect it should be

```
Outputs:
  Attribute: pet
  Key: my_pet
  Value: adjusted-platypus
```

Perhaps that's in the Rosemary's module code rather than the Operator.

<img width="817" alt="Screenshot 2019-12-18 06 55 14" src="https://user-images.githubusercontent.com/1139532/71097536-f8a17b00-2164-11ea-9f7e-d60c0001f7ef.png">
