### ISSUE TITLE
Support workspace notifications

### ISSUE THREAD

**Issue by rojopolis** [hashicorp/terraform-k8s#46]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform Cloud can send notifications on state change events, however these are configured per workspace.  Since the Operator "owns" the workspace it must be responsible for creating [Notification Configurations](https://www.terraform.io/docs/cloud/api/notification-configurations.html)
### Potential Workspace Configuration

```yaml
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: greetings
spec:
  organization: hashicorp-team-demo
  secretsMountPath: "/tmp/secrets"
  notifications:
    - name: "Notify Users"
       enabled: true
       destination-type: "slack"
       token: "1234abcd"
       triggers:
         - "run:errored"
         - "run:needs_attention"
       url: "https://webhook.url"
       users:
         - rojo@deba.cl
  module:
    source: "terraform-aws-modules/sqs/aws"
    version: "2.0.0"
  outputs:
    - key: url
      moduleOutputName: this_sqs_queue_id
    - key: arn
      moduleOutputName: this_sqs_queue_arn
  variables:
    - key: name
      value: greetings.fifo
      sensitive: false
      environmentVariable: false
    - key: fifo_queue
      value: "true"
      sensitive: false
      environmentVariable: false
    - key: AWS_DEFAULT_REGION
      valueFrom:
        configMapKeyRef:
          name: aws-configuration
          key: region
      sensitive: false
      environmentVariable: true
    - key: AWS_ACCESS_KEY_ID
      sensitive: true
      environmentVariable: true
    - key: AWS_SECRET_ACCESS_KEY
      sensitive: true
      environmentVariable: true
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true
```
