### ISSUE TITLE
Support VCS integration with TFC

### ISSUE THREAD

**Issue by redeux** [hashicorp/terraform-k8s#59]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add an option to support VCS integration with TFC, so that TFC can track changes in the git repo and automatically plan/apply them per the user's configuration.

Consider how to return the output to the Kubernetes configmap when the output changes from a run not initiated by the Operator.
 
### Potential Terraform Configuration

```yaml
spec:
  vcs-repo:
    identifier: "redeux/my-terraform-repo"
    oauth-token-id: "ot-hmAyP66qk2AMVdbJ"
    branch: ""
    default-branch: true
```

### References

https://www.terraform.io/docs/cloud/run/ui.html#automatically-starting-runs
https://www.terraform.io/docs/cloud/api/workspaces.html#update-a-workspace
