### ISSUE TITLE
Terraform Operator can't connect to a TFE instance, signed by a private CA

### ISSUE THREAD

**Issue by CodyKurtz** [hashicorp/terraform-k8s#60]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### terraform-k8s, Helm, & Kubernetes Version
terraform-k8s: hashicorp/terraform-k8s:0.1.5-alpha

helm version: 

version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Kubernetes Version: 

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-06-03T04:00:21Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

### Affected Resource(s)

ALL

### Helm Values

```yaml
# Available parameters and their default values for the Terraform chart.

# global holds values that affect multiple components of the chart.
global:
  # enabled is the master enabled/disabled setting.
  # If true, all Terraform Kubernetes integrations will be enabled.
  # If false, no components will be installed by default and per-component
  # opt-in is required, such as by setting `syncWorkspace.enabled` to true.
  enabled: true

  # imageK8S is the name (and tag) of the terraform-k8s Docker image that
  # is used for functionality such as workspace sync. This can be overridden
  # per component.
  imageK8S: "hashicorp/terraform-k8s:0.1.5-alpha"

# syncWorkspace will run the workspace sync process to sync K8S Workspaces with
# Terraform Cloud workspaces.
#
# This process will deploy a Workspace Custom Resource Definition and
# Terraform Cloud Workspace Operator to the Kubernetes cluster. It requires
# a Kubernetes secret for Terraform Cloud access and sensitive variables.
syncWorkspace:
  # True if you want to enable the workspace sync. Set to "-" to inherit from
  # global.enabled.
  enabled: "-"
  image: null

  # k8WatchNamespace is the Kubernetes namespace to watch for workspace
  # changes and sync to Terraform Cloud. If this is not set then it will default
  # to the release namespace
  k8WatchNamespace: null

  # terraformVersion describes the version of Terraform to use for each workspace.
  # If this is not set then it will default to the latest version of Terraform
  # compiled with the operator.
  terraformVersion: latest
  # tfeAddress denotes the address in the form of https://tfe.local for
  # a Terraform Enterprise instance. If this is not set then it will default
  # to Terraform Cloud (https://app.terraform.io)
  tfeAddress: https://mytfeinstance.com

  # Log verbosity level. One of "trace", "debug", "info", "warn", or "error".
  # Defaults to "info".
  logLevel: null

  # Name and key of Kubernetes secret containing the Terraform CLI Configuration
  # Must have Terraform Cloud Team API Token 
  terraformRC:
    secretName: terraformrc
    secretKey: credentials

  # Name of Kubernetes secret containing keys and values of sensitive variables 
  sensitiveVariables:
    secretName: workspacesecrets

# Control whether a test Pod manifest is generated when running helm template.
# When using helm install, the test Pod is not submitted to the cluster so this
# is only useful when running helm template.
tests:
  enabled: true
  organization: tf-operator
  # moduleSource defaults to this repository.
  # moduleSource: git::https://github.com/hashicorp/terraform-helm.git//test/module

```

### Debug Output

https://gist.github.com/CodyKurtz/d33d0f5db20df82bc209c90c893378bf

### Expected Behavior

There should be a way to mount a private public CA certificate, so the Terraform Operator can accept a TLS connection to a Terraform Enterprise instance, signed by a private CA. 

### Actual Behavior

TF Operator cannot connect to TFE. 
### Steps to Reproduce

Deploy TF Operator with a TFE instance, that has a cert signed by a private CA.

### Important Factoids
None

### References

<!---

None

* #0000
